### ISSUE TITLE
java.lang.NoSuchFieldError: isFire

### ISSUE THREAD

**Issue by Krutoy242** [SokyranTheDragon/Minor-Integrations-and-Additions-MIA-#16]
This error dont causes crush. But im interested how this influence on my pack.

```
[16:17:16] [Client thread/ERROR] [jei]: Failed to register mod plugin: class com.github.sokyranthedragon.mia.integrations.jer.JeiJerIntegration$1
java.lang.NoSuchFieldError: isFire
	at com.github.sokyranthedragon.mia.integrations.iceandfire.JerIceAndFireIntegration.configureMob(JerIceAndFireIntegration.java:238) ~[JerIceAndFireIntegration.class:?]
	at com.github.sokyranthedragon.mia.integrations.jer.JustEnoughResources.initJerIntegration(JustEnoughResources.java:204) ~[JustEnoughResources.class:?]
	at com.github.sokyranthedragon.mia.integrations.jer.JeiJerIntegration$1.register(JeiJerIntegration.java:64) ~[JeiJerIntegration$1.class:?]
	at mezz.jei.startup.JeiStarter.registerPlugins(JeiStarter.java:213) [JeiStarter.class:?]
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:77) [JeiStarter.class:?]
	at mezz.jei.startup.ProxyCommonClient.loadComplete(ProxyCommonClient.java:136) [ProxyCommonClient.class:?]
	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:55) [JustEnoughItems.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
[...]
````

**Comment by SokyranTheDragon** [comment]
Well, seems like I either did not get an email about this issue, or I haven't noticed it... Thankfully, I noticed a message over at CurseForge, which made me realize there was an issue.

Anyway, I've fixed it quite a while ago. If it still happens (or anything related to that Ice and Fire update), please open another issue.
