### ISSUE TITLE
Invalid registration attempt for an Ore Dictionary item

### ISSUE THREAD

**Issue by Krutoy242** [SokyranTheDragon/Minor-Integrations-and-Additions-MIA-#23]
I have 16 barely similar blocks of warnings in `debug.log`:
```java
[16:27:26] [Client thread/WARN] [FML]: ****************************************
[16:27:26] [Client thread/WARN] [FML]: * Invalid registration attempt for an Ore Dictionary item with name doorWood has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
[16:27:26] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:665)
[16:27:26] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:651)
[16:27:26] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:649)
[16:27:26] [Client thread/WARN] [FML]: *  at com.github.sokyranthedragon.mia.integrations.biomesoplenty.BiomesOPlenty.init(BiomesOPlenty.java:67)
[16:27:26] [Client thread/WARN] [FML]: *  at com.github.sokyranthedragon.mia.integrations.base.ModIntegrator.init(ModIntegrator.java:211)
[16:27:26] [Client thread/WARN] [FML]: *  at com.github.sokyranthedragon.mia.proxy.CommonProxy.init(CommonProxy.java:115)...
[16:27:26] [Client thread/WARN] [FML]: ****************************************
```
Seems like the dont affect a game, but how to rid them, and what do they means?

**Comment by SokyranTheDragon** [comment]
I'll look into this soon. This shouldn't cause any issues at all, so it's nothing to worry about.
