### ISSUE TITLE
MIA broke Just Enough Resources with EnderIO installed

### ISSUE THREAD

**Issue by Krutoy242** [SokyranTheDragon/Minor-Integrations-and-Additions-MIA-#26]
With MIA and EnderIO installed (default configs), JER category in JEI dissapeared.

Without MIA and with:
<img src="https://i.imgur.com/naYE0x1.png" height=300><img src="https://i.imgur.com/PVs7EL6.png" height=300>

It can be fixed through config option:
```cs
    # Set to false to completely disable integration with JER
    B:"Enable JER integration"=false
```

Minimum mod list:
```
EnderCore-1.12.2-0.5.76
EnderIO-base-1.12.2-5.2.66
jei_1.12.2-4.16.1.301
JustEnoughResources-1.12.2-0.9.2.60
mia-1.12.2-0.2.0e
```

[debug.log](https://github.com/SokyranTheDragon/Minor-Integrations-and-Additions-MIA-/files/5758955/debug.log)

<sup><sub>I spend like 6 hours to find this error in my 400 mods pack... duh</sub></sup>

**Comment by Codetoil** [comment]
I think this is where it went wrong: 
```
[16:07:31] [Client thread/ERROR] [jei]: Failed to register mod plugin: class jeresources.jei.JEIConfig
java.lang.NoSuchFieldError: vanillaSwordSkullChance
	at com.github.sokyranthedragon.mia.integrations.ender_io.JerEnderIoIntegration.overrideExistingMobDrops(JerEnderIoIntegration.java:23) ~[JerEnderIoIntegration.class:?]
	at com.github.sokyranthedragon.mia.integrations.jer.JustEnoughResources.overrideMobDrop(JustEnoughResources.java:260) ~[JustEnoughResources.class:?]
	at com.github.sokyranthedragon.mia.integrations.jer.CustomLinkedHashSet.add(CustomLinkedHashSet.java:17) ~[CustomLinkedHashSet.class:?]
	at jeresources.registry.MobRegistry.registerMob(MobRegistry.java:25) ~[MobRegistry.class:?]
	at jeresources.compatibility.CompatBase.registerMob(CompatBase.java:29) ~[CompatBase.class:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_251]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_251]
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1699) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_251]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_251]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_251]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_251]
	at jeresources.compatibility.minecraft.MinecraftCompat.registerVanillaMobs(MinecraftCompat.java:46) ~[MinecraftCompat.class:?]
	at jeresources.compatibility.minecraft.MinecraftCompat.init(MinecraftCompat.java:34) ~[MinecraftCompat.class:?]
	at jeresources.compatibility.Compatibility.init(Compatibility.java:26) ~[Compatibility.class:?]
	at jeresources.proxy.CommonProxy.initCompatibility(CommonProxy.java:14) ~[CommonProxy.class:?]
	at jeresources.jei.JEIConfig.register(JEIConfig.java:50) ~[JEIConfig.class:?]
	at mezz.jei.startup.JeiStarter.registerPlugins(JeiStarter.java:213) [JeiStarter.class:?]
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:77) [JeiStarter.class:?]
	at mezz.jei.startup.ProxyCommonClient.loadComplete(ProxyCommonClient.java:136) [ProxyCommonClient.class:?]
	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:55) [JustEnoughItems.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_251]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_251]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_251]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:757) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_251]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	```

**Comment by SokyranTheDragon** [comment]
I believe this is caused due to more recent EnderIO versions that are not supported by this mod yet. Hopefully, I'll be able to fix this soon.

**Comment by SokyranTheDragon** [comment]
Should be fixed in the update that''s about to release.
