### ISSUE TITLE
Torches Crash: Cannot set property PropertyInteger to 10

### ISSUE THREAD

**Issue by Krutoy242** [SokyranTheDragon/Minor-Integrations-and-Additions-MIA-#30]
Playing on dedicated server crashing game with log:

```java
java.lang.IllegalArgumentException: Cannot set property PropertyInteger{name=variant, clazz=class java.lang.Integer, values=[0, 1]} to 10 on block mia:torch_gold, it is not an allowed value
    at pl.asie.foamfix.common.FoamyBlockState.withProperty(FoamyBlockState.java:57)
    at com.github.sokyranthedragon.mia.block.base.BlockBaseMetaTorch.getStateForPlacement(BlockBaseMetaTorch.java:63)
    at net.minecraft.block.Block.getStateForPlacement(Block.java:2273)
    at portablejim.bbw.core.WandWorker.getProperItemStack(WandWorker.java:84)
```

I though problem was with FoamFix, but removing mod and loading again still crash:
```java

java.lang.IllegalArgumentException: Cannot set property PropertyInteger{name=variant, clazz=class java.lang.Integer, values=[0, 1]} to 10 on block mia:torch_gold, it is not an allowed value
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.withProperty(BlockStateContainer.java:235)
    at com.github.sokyranthedragon.mia.block.base.BlockBaseMetaTorch.getStateForPlacement(BlockBaseMetaTorch.java:63)
    at net.minecraft.block.Block.getStateForPlacement(Block.java:2273)
    at portablejim.bbw.core.WandWorker.getProperItemStack(WandWorker.java:84)
    at portablejim.bbw.core.BlockEvents.blockHighlightEvent(BlockEvents.java:53)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_4280_BlockEvents_blockHighlightEvent_DrawBlockHighlightEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
```

This wasnt happens all the time. I was played several days already and used this torches much.
Now i can't join server, but other players play fine.

[Full debg.log](https://github.com/SokyranTheDragon/Minor-Integrations-and-Additions-MIA-/files/7602646/debug.zip)

### Update:

This happens when i look at Torch with Builder's Wand from [Better Builder's Wands](https://www.curseforge.com/minecraft/mc-mods/better-builders-wands) mod.

**Comment by SokyranTheDragon** [comment]
Been trying to look into it, but not exactly sure what's up yet. My guess so far: some sort of conflict in combination with FoamFix and/or OptiFine. Will try to look more into it, but can't guarantee anything.

**Comment by SokyranTheDragon** [comment]
Though recently I wasn't able to fully focus on this project, so not sure when I'll be able to take a deeper look.

**Comment by SokyranTheDragon** [comment]
Oh, sorry. Missed some stuff there, kinda skimmed a bit too much. Maybe not FoamFix, as you said you removed it. But yeah, not fully able to check it right now.

**Comment by SokyranTheDragon** [comment]
Fixed it. Uploaded it to CurseForge and it's currently under review. Should be up soon.
