### ISSUE TITLE
Incompat with `I&F: RLCraft Edition`

### ISSUE THREAD

**Issue by Krutoy242** [SokyranTheDragon/Minor-Integrations-and-Additions-MIA-#42]
[Ice & Fire: RLCraft Edition](https://www.curseforge.com/minecraft/mc-mods/iceandfire-rlcraft) is a maintained fork of IceAndFire that adds new features and backport ones implemented in newer MC versions.

I tried to install it on my [E2EE modpack](https://www.curseforge.com/minecraft/modpacks/enigmatica-2-expert-extended) and game crashed several times, until I disabled all MIA config options in I&F config section.
Crash report:
```ruby
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minor Integrations and Additions (mia)
Caused by: java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/item/IafItemRegistry
    at com.github.sokyranthedragon.mia.integrations.iceandfire.TConstructIceAndFireIntegration.init(TConstructIceAndFireIntegration.java:25)
    at com.github.sokyranthedragon.mia.integrations.tconstruct.TinkersConstruct.init(TinkersConstruct.java:94)
```
```ruby
java.lang.NoSuchFieldError: Class com.github.alexthe666.iceandfire.IceAndFire does not have member field 'net.minecraft.creativetab.CreativeTabs TAB_BLOCKS'
    at com.github.sokyranthedragon.mia.block.BlockPixieDustExtractor.<init>(BlockPixieDustExtractor.java:35)
    at com.github.sokyranthedragon.mia.block.BlockPixieDustExtractor.<init>(BlockPixieDustExtractor.java:29)
```
[crash-2024-11-02_10.22.08-client.txt](https://github.com/user-attachments/files/17606155/crash-2024-11-02_10.22.08-client.txt)

[crash-2024-11-02_10.05.53-client.txt](https://github.com/user-attachments/files/17606154/crash-2024-11-02_10.05.53-client.txt)

I know its not fail of MIA, since its like RLCraft rewritten lot of classes. Similar problem happen with [JustEnoughMagiculture](https://github.com/Invadermonky/JustEnoughMagiculture/issues/19) mod.

**Comment by SokyranTheDragon** [comment]
Unlikely to be fixed, considering that I'm unable to get the tools required to build the mod to work. Neither the updated nor the outdated ones haven't worked for me, so the mod will likely remain as-is.
